# Generated by Django 5.0.3 on 2024-03-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='upload',
            field=models.FileField(upload_to='static/media/uploads/'),
        ),
    ]
