# Generated by Django 5.0.3 on 2024-03-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_site', '0002_alter_ad_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
