# Generated by Django 4.2.7 on 2024-01-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_subscription_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
